### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by djsabelo** [henripal/labnotebook#6]
Good morning,

I was trying to install and try labnotebook but an error prevented me from continuing, could you please guide me in solving the problem, if possible?

when I do pip install. or pip3 install . this error follows:

```

Processing /home/belo/Libs/labnotebook
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-kspoor7r-build/setup.py", line 19, in <module>
        'start_backend = labnotebook.backend.api:start_backend'
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-kspoor7r-build/


```

Best Regards,

David Belo

**Comment by henripal** [comment]
Try upgrading setuptools: 
```
pip install setuptools --upgrade
```
or
```
sudo pip install setuptools --upgrade
```

Let me know!

**Comment by henripal** [comment]
Great, thanks
